name: "Community Verified: Submission"
description: "Submit a business you don't own. Provide evidence links (2+)."
title: "[Community] <Business name> - <City, Country>"
labels: ["submission", "community", "verification"]

body:
  - type: markdown
    attributes:
      value: |
        Provide accurate info. One business per issue.

  - type: input
    id: business_name
    attributes:
      label: "Business name"
      placeholder: "Example Coffee Roasters"
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: "Address"
      description: "Use full address. Format: Street number + street, City, STATE ZIP, Country"
      placeholder: "350 5th Ave, New York, NY 10118, USA"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: "Official website URL (if any)"
      placeholder: "https://example.com"
    validations:
      required: false

  - type: textarea
    id: payments
    attributes:
      label: "Accepted crypto (assets/chains)"
      description: |
        If known, list formats like:
        - BTC (Lightning)
        - ETH (EVM mainnet)
        - USDT (Tron)
      placeholder: "- BTC (Lightning)"
    validations:
      required: false

  - type: textarea
    id: evidence_urls
    attributes:
      label: "Evidence URLs (2+)"
      description: "Links that prove crypto acceptance (menu, signage, posts, provider pages, etc.). One per line."
      placeholder: "https://...\nhttps://..."
    validations:
      required: true

  - type: textarea
    id: profile_summary
    attributes:
      label: "Profile summary (for map card)"
      description: "Max ~300 chars. Public text you own the rights to."
      placeholder: "They accept BTC (Lightning). Please confirm at checkout."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Images
        Attach up to **4 images** directly to this issue (drag & drop).  
        GitHub will auto-host them (user-images URLs).  
        They will be collected into your gallery automatically.  
        → No need to paste URLs manually.

        📸 **Your uploaded images will appear below once the upload finishes.**  
        *(If you don't see a preview yet, switch to the “Preview” tab.)*

  - type: checkboxes
    id: consent
    attributes:
      label: "Rights & consent"
      options:
        - label: "I have the rights to the text/images submitted and grant CryptoPayMap a non-exclusive, free license to display them."
          required: true
        - label: "I understand the submission may be reviewed and rejected if unverifiable."
          required: true
