name: "Community Verified: Submission"
description: Submit a business you have evidence for (not the owner). Needs 2+ independent sources.
title: "[Community] <Business name> - <City, Country>"
labels: ["submission", "community", "verification"]
body:
  - type: markdown
    attributes:
      value: |
        Provide accurate info. One business per issue.

  - type: input
    id: business_name
    attributes:
      label: Business name
      placeholder: Example Coffee Roasters
    validations:
      required: true

  - type: input
    id: address
    attributes:
      label: Address
      placeholder: "350 5th Ave, New York, NY 10118, USA"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Official website URL (if known)
      placeholder: https://example.com
    validations:
      required: false

  - type: textarea
    id: payments
    attributes:
      label: Accepted crypto (assets/chains)
      description: |
        Example:
        - BTC (Lightning)
        - ETH (EVM mainnet)
      placeholder: "- BTC (Lightning)\n- ETH (EVM mainnet)"
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence URLs (2+ required)
      description: Proof that crypto is accepted (checkout page, social post, receipt photo, etc.)
      placeholder: |
        https://example.com/payments
        https://x.com/.../status/12345
    validations:
      required: true

  - type: dropdown
    id: already_listed
    attributes:
      label: Is this business already listed on CryptoPayMap?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: listed_url_or_id
    attributes:
      label: If YES: paste the map URL or place ID
      placeholder: "https://... or us-nyc-abc123"
    validations:
      required: false

  - type: textarea
    id: profile_summary
    attributes:
      label: Profile summary (for map card)
      description: Max ~300 chars.
      placeholder: "This cafe accepts BTC and ETH."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Images
        Attach up to **4 images** directly to this issue (drag & drop).
        GitHub will auto-host them (user-images URLs).
        They will be collected automatically.
        → No need to paste URLs manually.

  - type: checkboxes
    id: consent
    attributes:
      label: Rights & consent
      options:
        - label: I have the rights to the text/images submitted and grant CryptoPayMap a non-exclusive, free license to display them.
          required: true
        - label: I understand the submission may be reviewed and rejected if unverifiable.
          required: true
