import { and, asc, eq, ilike, inArray, isNull } from 'drizzle-orm';
import { createDerivedStagingServiceIdentity } from '../src/admin/access/identity';
import { authorizeEvidenceReview, readEvidenceReviewAuthorizationPolicy } from '../src/admin/evidence-review/authorization';
import { createEvidenceReviewDecisionService } from '../src/admin/evidence-review/decision';
import { createDrizzleEvidenceReviewBackend } from '../src/admin/evidence-review/drizzle-backend';
import { authorizeCandidatePromotion, readCandidatePromotionAuthorizationPolicy } from '../src/admin/promotion/authorization';
import { createCandidatePromotionService } from '../src/admin/promotion/candidate-promotion';
import { createDrizzleCandidatePromotionBackend } from '../src/admin/promotion/drizzle-candidate-promotion-backend';
import { createDatabase } from '../src/db/client';
import { acceptanceClaims, assets, candidatePromotionDecisions, candidateSourceRecords, claimAssets, evidence, networks, paymentMethods, sourceCandidates, sourceRecords, sources } from '../src/db/schema';

declare const process: { env: Record<string, string | undefined> };

const TARGET = 'fixed-review-staging';
const CHIPOTLE_URL = 'https://ir.chipotle.com/2022-07-25-CHIPOTLE-ENCOURAGES-FANS-TO-BUY-THE-DIP-WITH-NEW-200%2C000-CRYPTO-GAME-AND-1-CENT-GUAC-FOR-NATIONAL-AVOCADO-DAY';
const FLEXA_CHIPOTLE_URL = 'https://flexa.co/newsroom/mini-apps';
const FLEXA_CURRENCIES_URL = 'https://docs.flexa.co/payments/currencies';
const MAX_TARGETS = 40;
type JsonRecord = Record<string, unknown>;

function record(value: unknown): JsonRecord { return value !== null && typeof value === 'object' && !Array.isArray(value) ? value as JsonRecord : {}; }
async function deterministicUuid(label: string): Promise<string> { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(label)); const bytes = new Uint8Array(digest).slice(0,16); bytes[6]=((bytes[6]??0)&0x0f)|0x80; bytes[8]=((bytes[8]??0)&0x3f)|0x80; const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join(''); return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`; }
function pageText(html: string): string { return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim().toLowerCase(); }
async function fetchText(url: string) { const response=await fetch(url,{redirect:'follow',signal:AbortSignal.timeout(20_000),headers:{'user-agent':'CryptoPayMap-physical-source-review/1.0',accept:'text/html,text/plain;q=0.9,*/*;q=0.1'}}); if(!response.ok) throw new Error(`Source verification failed: HTTP ${response.status} ${url}`); return {url:response.url,body:await response.text(),fetchedAt:new Date()}; }
function verifyChipotle(body:string){const v=pageText(body); if(!/accepts digital currency[^.]{0,120}cryptocurrency[^.]{0,120}nationwide/.test(v)) throw new Error('Chipotle first-party page no longer verifies nationwide cryptocurrency acceptance.'); if(!/bitcoin/.test(v)||!/flexa/.test(v)) throw new Error('Chipotle first-party page no longer verifies Bitcoin through Flexa.');}
function verifyFlexaMerchant(body:string){const v=pageText(body); if(!/chipotle/.test(v)||!/digital asset payments acceptance/.test(v)) throw new Error('Current Flexa page no longer verifies Chipotle digital-asset acceptance.');}
function verifyFlexaBitcoin(body:string){const v=pageText(body); if(!/bitcoin/.test(v)||!/lightning/.test(v)||!/payment currencies/.test(v)) throw new Error('Current Flexa currencies page no longer verifies Bitcoin/Lightning payment support.');}
async function ensureSource(db:ReturnType<typeof createDatabase>,sourceType:'official_site'|'processor',name:string,baseUrl:string){let row=(await db.select().from(sources).where(and(eq(sources.sourceType,sourceType),eq(sources.name,name))).limit(1))[0]; if(!row)[row]=await db.insert(sources).values({sourceType,name,baseUrl,isActive:true}).returning(); if(!row)throw new Error(`Failed to resolve source ${name}.`); return row;}
async function ensureSourceRecord(db:ReturnType<typeof createDatabase>,input:{sourceId:string;externalId:string;sourceUrl:string;officialDomain:string;rawPayload:JsonRecord;fetchedAt:Date}){await db.insert(sourceRecords).values(input).onConflictDoNothing(); const [row]=await db.select().from(sourceRecords).where(and(eq(sourceRecords.sourceId,input.sourceId),eq(sourceRecords.externalId,input.externalId))).limit(1); if(!row)throw new Error(`Failed source record ${input.externalId}`); return row;}

async function main(){
 if(process.env.CPM_CANDIDATE_ACQUISITION_TARGET!==TARGET)throw new Error(`Refusing mutation outside ${TARGET}.`);
 const databaseUrl=process.env.DATABASE_URL?.trim(); if(!databaseUrl)throw new Error('DATABASE_URL is required.'); const db=createDatabase(databaseUrl);
 const promotionPolicy=readCandidatePromotionAuthorizationPolicy({CPM_ADMIN_CANDIDATE_PROMOTE_SUBJECTS:process.env.CPM_ADMIN_CANDIDATE_PROMOTE_SUBJECTS});
 const evidencePolicy=readEvidenceReviewAuthorizationPolicy({CPM_ADMIN_EVIDENCE_REVIEW_SUBJECTS:process.env.CPM_ADMIN_EVIDENCE_REVIEW_SUBJECTS});
 const reviewer=createDerivedStagingServiceIdentity('reviewer'); if(!promotionPolicy.configured||!promotionPolicy.allowedSubjects.has(reviewer.subject))throw new Error('Staging reviewer not authorized for promotion.'); if(!evidencePolicy.configured||!evidencePolicy.allowedSubjects.has(reviewer.subject))throw new Error('Staging reviewer not authorized for Evidence review.');
 const [chipotle,flexaMerchant,flexaCurrencies]=await Promise.all([fetchText(CHIPOTLE_URL),fetchText(FLEXA_CHIPOTLE_URL),fetchText(FLEXA_CURRENCIES_URL)]); verifyChipotle(chipotle.body); verifyFlexaMerchant(flexaMerchant.body); verifyFlexaBitcoin(flexaCurrencies.body);
 const merchantSource=await ensureSource(db,'official_site','Chipotle official site','https://www.chipotle.com/'); const processorSource=await ensureSource(db,'processor','Flexa','https://flexa.co/');
 const merchantRecord=await ensureSourceRecord(db,{sourceId:merchantSource.id,externalId:'chipotle:nationwide-crypto-flexa:2022-07-25',sourceUrl:CHIPOTLE_URL,officialDomain:'chipotle.com',rawPayload:{discovery:'merchant_official_crypto_announcement',merchant:'Chipotle',scope:'nationwide',asset:'bitcoin',processor:'Flexa',fetchedUrl:chipotle.url},fetchedAt:chipotle.fetchedAt});
 const processorRecord=await ensureSourceRecord(db,{sourceId:processorSource.id,externalId:'flexa:chipotle-current-digital-asset-acceptance',sourceUrl:FLEXA_CHIPOTLE_URL,officialDomain:'flexa.co',rawPayload:{discovery:'processor_current_merchant_confirmation',merchant:'Chipotle',scope:'in_person',fetchedUrl:flexaMerchant.url},fetchedAt:flexaMerchant.fetchedAt});
 const currenciesRecord=await ensureSourceRecord(db,{sourceId:processorSource.id,externalId:'flexa:current-bitcoin-lightning-currencies',sourceUrl:FLEXA_CURRENCIES_URL,officialDomain:'flexa.co',rawPayload:{discovery:'processor_supported_currencies',asset:'bitcoin',networks:['bitcoin','lightning'],fetchedUrl:flexaCurrencies.url},fetchedAt:flexaCurrencies.fetchedAt});
 const [[bitcoin],[lightning],[lightningInvoice]]=await Promise.all([db.select({id:assets.id}).from(assets).where(and(eq(assets.slug,'bitcoin'),eq(assets.status,'active'))).limit(1),db.select({id:networks.id}).from(networks).where(and(eq(networks.slug,'lightning'),eq(networks.status,'active'))).limit(1),db.select({id:paymentMethods.id}).from(paymentMethods).where(and(eq(paymentMethods.slug,'lightning_invoice'),eq(paymentMethods.status,'active'))).limit(1)]); if(!bitcoin||!lightning||!lightningInvoice)throw new Error('BTC/Lightning staging registries are not ready.');
 const candidates=await db.select({id:sourceCandidates.id,status:sourceCandidates.candidateStatus,updatedAt:sourceCandidates.updatedAt,canonicalEntityId:sourceCandidates.canonicalEntityId,canonicalLocationId:sourceCandidates.canonicalLocationId}).from(sourceCandidates).where(and(eq(sourceCandidates.candidateType,'physical_place'),ilike(sourceCandidates.normalizedName,'%chipotle%'),isNull(sourceCandidates.duplicateGroupId),inArray(sourceCandidates.candidateStatus,['new','triaged','promoted']))).orderBy(asc(sourceCandidates.id)).limit(MAX_TARGETS);
 const counters={candidates:candidates.length,verifiedOfficialLocations:0,skippedMissingOrigin:0,promoted:0,alreadyPromoted:0,confirmed:0,alreadyConfirmed:0,officialEvidenceCreated:0,processorEvidenceCreated:0};
 for(const candidate of candidates){
  const relations=await db.select({sourceRecordId:candidateSourceRecords.sourceRecordId,relationship:candidateSourceRecords.relationship,sourceUrl:sourceRecords.sourceUrl,rawPayload:sourceRecords.rawPayload}).from(candidateSourceRecords).innerJoin(sourceRecords,eq(sourceRecords.id,candidateSourceRecords.sourceRecordId)).where(eq(candidateSourceRecords.candidateId,candidate.id)).orderBy(asc(candidateSourceRecords.sourceRecordId));
  const origin=relations.find(r=>r.relationship==='origin'&&record(r.rawPayload).sourceSystem==='chipotle_official_location_directory'); const seed=record(record(origin?.rawPayload).reviewSeed); const name=typeof seed.name==='string'&&seed.name.trim()?seed.name.trim():'Chipotle Mexican Grill'; const latitude=typeof seed.latitude==='number'?seed.latitude:null; const longitude=typeof seed.longitude==='number'?seed.longitude:null; const address=typeof seed.address==='string'?seed.address.trim():null; const city=typeof seed.city==='string'?seed.city.trim():null; const state=typeof seed.state==='string'?seed.state.trim():null; const postal=typeof seed.postalCode==='string'?seed.postalCode.trim():null; const website=typeof seed.websiteUrl==='string'?seed.websiteUrl.trim():origin?.sourceUrl ?? null;
  if(!origin||latitude===null||longitude===null||!website){counters.skippedMissingOrigin++;continue;} counters.verifiedOfficialLocations++;
  await db.insert(candidateSourceRecords).values([{candidateId:candidate.id,sourceRecordId:merchantRecord.id,relationship:'supporting'},{candidateId:candidate.id,sourceRecordId:processorRecord.id,relationship:'supporting'},{candidateId:candidate.id,sourceRecordId:currenciesRecord.id,relationship:'supporting'}]).onConflictDoNothing();
  const officialEvidenceId=await deterministicUuid(`chipotle:official:evidence:${candidate.id}`); const processorEvidenceId=await deterministicUuid(`chipotle:flexa:evidence:${candidate.id}`);
  if(!(await db.select({id:evidence.id}).from(evidence).where(eq(evidence.id,officialEvidenceId)).limit(1))[0]){await db.insert(evidence).values({id:officialEvidenceId,sourceRecordId:merchantRecord.id,evidenceKind:'official_payment_page',evidenceClass:'a',sourceType:'official_page',originRole:'merchant_side',polarity:'supporting',sourceName:'Chipotle official nationwide crypto announcement',sourceUrl:CHIPOTLE_URL,observedAt:chipotle.fetchedAt,fetchedAt:chipotle.fetchedAt,summary:'Chipotle states that it accepts digital currency including cryptocurrency nationwide through Flexa, including Bitcoin.',visibility:'private',reviewStatus:'pending'}); counters.officialEvidenceCreated++;}
  if(!(await db.select({id:evidence.id}).from(evidence).where(eq(evidence.id,processorEvidenceId)).limit(1))[0]){await db.insert(evidence).values({id:processorEvidenceId,sourceRecordId:processorRecord.id,evidenceKind:'processor_case_study',evidenceClass:'b',sourceType:'processor',originRole:'processor_side',polarity:'supporting',sourceName:'Flexa current Chipotle digital-asset acceptance',sourceUrl:FLEXA_CHIPOTLE_URL,observedAt:flexaMerchant.fetchedAt,fetchedAt:flexaMerchant.fetchedAt,summary:'Flexa currently identifies Chipotle as a merchant accepting digital asset payments; current Flexa currency documentation lists Bitcoin with Lightning support.',visibility:'private',reviewStatus:'pending',independenceKey:'processor:flexa.co'}); counters.processorEvidenceCreated++;}
  let claimId:string;
  if(candidate.status==='promoted'){const [p]=await db.select({claimId:candidatePromotionDecisions.claimId}).from(candidatePromotionDecisions).where(eq(candidatePromotionDecisions.candidateId,candidate.id)).limit(1); if(!p)throw new Error('Promoted Candidate missing promotion decision.'); claimId=p.claimId;counters.alreadyPromoted++;}
  else { if(candidate.canonicalEntityId||candidate.canonicalLocationId)throw new Error('Unpromoted Candidate has canonical links.'); const entityId=await deterministicUuid(`chipotle:entity:${candidate.id}`); const locationId=await deterministicUuid(`chipotle:location:${candidate.id}`); claimId=await deterministicUuid(`chipotle:claim:${candidate.id}`); const claimAssetId=await deterministicUuid(`chipotle:claim-asset:${candidate.id}:lightning`); const requestId=await deterministicUuid(`chipotle:promotion:${candidate.id}`); const promotedAt=new Date(Math.max(Date.now(),candidate.updatedAt.getTime()+1000)); const context=authorizeCandidatePromotion(reviewer,promotionPolicy,requestId); const receipt=await createCandidatePromotionService(createDrizzleCandidatePromotionBackend(db)).promote(context,{candidateId:candidate.id,expectedCandidateType:'physical_place',expectedCandidateUpdatedAt:candidate.updatedAt.toISOString(),promotedAt:promotedAt.toISOString(),entity:{id:entityId,value:{entityType:'merchant',name:'Chipotle Mexican Grill',slug:null,legalName:null,websiteUrl:'https://www.chipotle.com/',countryCode:'US',entityStatus:'active',visibility:'hidden'}},location:{id:locationId,value:{name,slug:`chipotle-${new URL(website).pathname.split('/').filter(Boolean).at(-1)??candidate.id}`.slice(0,64),addressLine:address,locality:city,region:state,postalCode:postal,countryCode:'US',latitude,longitude,locationStatus:'active',visibility:'hidden',websiteUrl:website,phone:null,description:null,openingHours:null,amenities:[],socialLinks:[],osmType:null,osmId:null}},claim:{id:claimId,value:{entityId,locationId,claimScope:'location_specific',routeType:'direct_wallet',acceptanceScope:'all_checkout',claimStatus:'candidate',visibility:'hidden',customerPaysCrypto:true,merchantExplicitlyAcceptsCrypto:true,processorId:null,howToPay:'At checkout, use a Flexa-enabled payment experience and select a supported digital asset. Bitcoin is supported by Flexa, including Lightning-compatible payment rails.',instructionsLanguage:'en',merchantReceives:'not_publicly_confirmed',restrictions:'Availability is subject to the current Flexa-enabled checkout experience at Chipotle.',firstConfirmedAt:null,lastConfirmedAt:null,nextReviewAt:null,endedAt:null,endedReason:null}},claimAssets:[{id:claimAssetId,value:{claimId,assetId:bitcoin.id,networkId:lightning.id,paymentMethodId:lightningInvoice.id,contractAddress:null,isPrimary:true,notes:'Flexa currently lists Bitcoin with Lightning network support.'}}],sourceRecordIds:[...new Set([...relations.map(r=>r.sourceRecordId),merchantRecord.id,processorRecord.id,currenciesRecord.id])]}); if(receipt.state==='committed')counters.promoted++; }
  const [claim]=await db.select({id:acceptanceClaims.id,claimStatus:acceptanceClaims.claimStatus,visibility:acceptanceClaims.visibility,updatedAt:acceptanceClaims.updatedAt}).from(acceptanceClaims).where(eq(acceptanceClaims.id,claimId)).limit(1); if(!claim)throw new Error('Promoted claim missing.'); if(claim.claimStatus==='confirmed'){counters.alreadyConfirmed++;continue;}
  const [officialRow]=await db.select({claimId:evidence.claimId,reviewStatus:evidence.reviewStatus,visibility:evidence.visibility,updatedAt:evidence.updatedAt}).from(evidence).where(eq(evidence.id,officialEvidenceId)).limit(1); if(!officialRow)throw new Error('Official Evidence missing.'); let evidenceUpdatedAt=officialRow.updatedAt; if(officialRow.claimId===null){const bindAt=new Date(Math.max(Date.now(),claim.updatedAt.getTime()+1000,officialRow.updatedAt.getTime()+1000)); const [bound]=await db.update(evidence).set({claimId,updatedAt:bindAt}).where(and(eq(evidence.id,officialEvidenceId),isNull(evidence.claimId))).returning({updatedAt:evidence.updatedAt}); if(!bound)throw new Error('Failed to bind official Evidence.'); evidenceUpdatedAt=bound.updatedAt;} await db.update(evidence).set({claimId}).where(and(eq(evidence.id,processorEvidenceId),isNull(evidence.claimId)));
  const acceptedRows=await db.select({id:evidence.id}).from(evidence).where(and(eq(evidence.claimId,claimId),eq(evidence.reviewStatus,'accepted'))).orderBy(asc(evidence.id)); const assetRows=await db.select({id:claimAssets.id}).from(claimAssets).where(eq(claimAssets.claimId,claimId)).orderBy(asc(claimAssets.id)); const decidedAt=new Date(Math.max(Date.now(),claim.updatedAt.getTime()+1000,evidenceUpdatedAt.getTime()+1000)); const nextReviewAt=new Date(decidedAt.getTime()+30*24*60*60*1000); const requestId=await deterministicUuid(`chipotle:evidence-review:${candidate.id}`); const context=authorizeEvidenceReview(reviewer,evidencePolicy,requestId); const receipt=await createEvidenceReviewDecisionService(createDrizzleEvidenceReviewBackend(db)).decide(context,{evidenceId:officialEvidenceId,claimId,expectedEvidenceUpdatedAt:evidenceUpdatedAt.toISOString(),expectedEvidenceReviewStatus:'pending',expectedClaimUpdatedAt:claim.updatedAt.toISOString(),expectedClaimStatus:'candidate',expectedClaimVisibility:'hidden',expectedAcceptedEvidenceIds:acceptedRows.map(r=>r.id),expectedClaimAssetIds:assetRows.map(r=>r.id),decidedAt:decidedAt.toISOString(),disposition:'accepted',finding:'supports_claim',claimAction:'confirm',reasonCode:'official_payment_page_verified',publicSummary:null,internalNote:'Confirmed from Chipotle first-party nationwide cryptocurrency acceptance, current Flexa Chipotle merchant confirmation, current Flexa Bitcoin/Lightning currency support, and the location-specific official Chipotle directory.',nextReviewAt:nextReviewAt.toISOString(),endedReason:null}); if(receipt.state==='committed'&&receipt.claimStatus==='confirmed')counters.confirmed++;
 }
 console.log(JSON.stringify({target:TARGET,merchant:'Chipotle',officialNationwideCryptoReverified:true,currentFlexaChipotleReverified:true,currentFlexaBitcoinLightningReverified:true,maxTargets:MAX_TARGETS,...counters,automaticPublicVisibility:false,candidatePayloadExposed:false}));
}
await main();