name: ingest-submission

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch: {}

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  ingest:
    name: Ingest issue -> build submission JSON -> open PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node → pnpm → install（npm ciは使わない）
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm@10
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # 実体の intake スクリプトを実行（パスはリポジトリに合わせて）
      - name: Build submissions from issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_ACTION: ${{ github.event.action }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
        run: |
          # 例: ラベルが owner のときだけ処理（必要に応じて条件調整）
          if echo "${ISSUE_LABELS}" | grep -qi '\bowner\b'; then
            pnpm tsx scripts/issue_intake.ts --issue $ISSUE_NUMBER
          else
            echo "No owner label; skipping intake."
          fi

      # intake が作ったファイルをブランチにコミットして PR を作る例
      - name: Create PR with inbox files
        if: success()
        run: |
          set -e
          BR="intake/issue-${{ github.event.issue.number }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          git add inbox/submissions || true
          git add inbox/rejects || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(intake): issue #${{ github.event.issue.number }}"
          git push -u origin "$BR"
          gh pr create --fill || true
