name: verify-places

on:
  schedule:
    - cron: "0 3 * * *"   # daily at 03:00 UTC (JST 12:00)
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  run-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i jsdom@24

      - name: Run verifier
        run: node tools/verify/scan.mjs

      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/verify-update
          commit-message: "chore(verify): auto-update verification metadata and labels"
          title: "Auto: verification update"
          body: "Nightly bot updated verification labels/evidence. Review & merge."
          labels: verification, bot
